/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'repair' : IDL.Null,
  'cleaning' : IDL.Null,
  'maintenance' : IDL.Null,
  'installation' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'preferredDate' : IDL.Text,
  'address' : IDL.Text,
  'preferredTime' : IDL.Text,
  'contactNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'repair' : IDL.Null,
    'cleaning' : IDL.Null,
    'maintenance' : IDL.Null,
    'installation' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'preferredDate' : IDL.Text,
    'address' : IDL.Text,
    'preferredTime' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };